
name: Test Workflow

on:
    push:
        branches:
            - main
        paths:
            - folder/**

env:
    model_dirs: 'folder/'
    
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: List edited files
#         id: changed_files
#         run: |
#           # Fetch the commits referenced by the event so we can diff them
#           git fetch --no-tags --prune origin +${{ github.event.before }}:before +${{ github.event.after }}:after
          
#           echo "Files changed in this push:"
#           git diff --name-only before after
#           echo "files=$(git diff --name-only before after | xargs)" >> $GITHUB_OUTPUT
  
#       - name: Determine model dir
#         id: determine_dir
#         shell: bash
#         run: |
#           # Get the list of model dirs being monitored
#           monitored_paths=$(echo "${{ env.model_dirs }}" | tr "," " ")
#           echo "Monitored model dirs: $monitored_paths"
#           echo "Changed files: ${{ steps.changed_files.outputs.files }}"

#           # Loop through each path
#           for path in $monitored_paths
#           do
#             # Check if the modified files include this path
#             if echo "${{ steps.changed_files.outputs.files }}" | grep -q "$path"; then
#               # Set the output variable and exit the loop
#               echo "modified model dir is $path"
#               echo "model_dir=$path" >> $GITHUB_OUTPUT
#               break
#             fi
#           done
    
